/*
 * This source file was generated by the Gradle 'init' task
 */
package main.java.CSE3241Project;

import java.util.Scanner;

import main.java.CSE3241Project.models.DataManager;

public class App {

    public static void addRecords(Scanner in) {
        NavigationMessages.selectRecordType();
        int userSelectionChoice = -1;
        userSelectionChoice = Integer.parseInt(in.nextLine());
        switch (userSelectionChoice) {
            case 1:
                DataManager.addToWarehouses(in);
                break;
            case 2:
//                data.addToMembers(in);
                break;
            case 3:
            	DataManager.addRentableEquipment(in);
                break;
        }
    }

    public static void deleteRecords(Scanner in) {
        NavigationMessages.selectRecordType();
        int userSelectionChoice = -1;
        userSelectionChoice = Integer.parseInt(in.nextLine());
        switch (userSelectionChoice) {
            case 1:
                System.out.println("Enter ID Warehouse to Delete");
                String warehouseID = in.nextLine();
//                data.deleteFromWarehouses(warehouseID);
                break;
            case 2:
                System.out.println("Enter ID of Member to Delete");
                String memberID = in.nextLine();
//                data.deleteFromMembers(memberID);
                break;
            case 3:
                System.out.println("Enter SERIAL NUMBER of Equipment to Delete");
                String itemSerialNumber = in.nextLine();
//                data.deleteFromRentableEquipment(itemSerialNumber);
                break;
        }
    }

    public static void searchRecords(Scanner in) {
        NavigationMessages.selectRecordType();
        int userSelectionChoice = -1;
        userSelectionChoice = Integer.parseInt(in.nextLine());
        switch (userSelectionChoice) {
            case 1:
                System.out.println("Enter ID Warehouse to Retrieve");
                String warehouseID = in.nextLine();
                System.out.println();
//                DataManager.searchForSpecificWarehouse(warehouseID);
                break;
            case 2:
                System.out.println("Enter ID of Member to Retrieve");
                String memberID = in.nextLine();
                System.out.println();
//                data.searchForSpecificMember(memberID);
                break;
            case 3:
                System.out.println("Enter SERIAL NUMBER of Equipment to Retrieve");
                String itemSerialNumber = in.nextLine();
                System.out.println();
//                data.searchForSpecificRentableEquipment(itemSerialNumber);
                break;
        }
    }
    

    public static void main(String[] args) {
    	DataManager.dbInit();
        int userSelectionChoice = -1;
        Scanner in = new Scanner(System.in);
       

        while (userSelectionChoice != 0) {
        NavigationMessages.welcomeNavigation();
        String input = in.nextLine();

        try {
            // Try to parse the input
            userSelectionChoice = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            // Handle the case where input is not a valid number
            System.out.println("Invalid input. Please enter a number.");
            continue; // Continue the loop to re-prompt for input
        }

        switch (userSelectionChoice) {
            case 1:
                addRecords(in);
                userSelectionChoice = -1;
                break;
            
            case 2:
                deleteRecords(in);
                userSelectionChoice = -1;
                break;
            
            case 3:
                searchRecords(in);
                userSelectionChoice = -1;
                break;
            
            case 4: 
                System.out.println("Equipment Rented.");
                userSelectionChoice = -1;
                break;
            case 5: 
                System.out.println("Equipment Picked Up.");
                userSelectionChoice = -1;
                break;

            case 6: 
                System.out.println("Equipment Returned.");
                userSelectionChoice = -1;
                break;

            case 7: 
                System.out.println("Equipment Delivered.");
                userSelectionChoice = -1;
                break;

            default:
                break;
        }
    }
        in.close();
    }
}